"""
Feature definitions for transactions-online example.

This example demonstrates building features to both offline and online stores.
Uses a simplified user_spend feature for clarity.
"""

from datetime import timedelta

import polars as pl

import mlforge as mlf

### Source Definition

source = mlf.Source("data/transactions.parquet")

### Entity Definitions

user = mlf.Entity(
    name="user",
    join_key="user_id",
    from_columns=["first", "last", "dob"],
)

### Metrics

# Define rolling aggregations over 7 and 30 day windows
spend_metrics = mlf.Rolling(
    windows=[timedelta(days=7), "30d"],
    aggregations={"amt": ["count", "sum"]},
)


@mlf.feature(
    source=source,
    entities=[user],
    tags=["users"],
    description="User spending aggregations for real-time serving",
    timestamp="transaction_date",
    interval=timedelta(days=1),
    metrics=[spend_metrics],
)
def user_spend(df: pl.DataFrame) -> pl.DataFrame:
    """
    Compute user spend aggregations.

    Transforms raw transactions into daily user spend metrics
    with 7-day and 30-day rolling windows.
    """
    # user_id is auto-generated by the engine from the user entity
    return df.select(
        pl.col("user_id"),
        pl.col("trans_date_trans_time")
        .str.to_datetime("%Y-%m-%d %H:%M:%S")
        .alias("transaction_date"),
        pl.col("amt"),
    )
