from datetime import timedelta

import polars as pl

import mlforge as mlf

### Source Definition

source = mlf.Source("data/transactions.parquet")

### Entity Definitions

merchant = mlf.Entity(
    name="merchant",
    join_key="merchant_id",
    from_columns=["merchant"],
)

account = mlf.Entity(
    name="account",
    join_key="account_id",
    from_columns=["cc_num"],
)

user = mlf.Entity(
    name="user",
    join_key="user_id",
    from_columns=["first", "last", "dob"],
)

### Metrics

spend_metrics = mlf.Rolling(
    windows=[timedelta(days=7), "30d", "90d"],
    aggregations={"amt": ["count", "mean", "sum"]},
)


### MERCHANT FEATURES


@mlf.feature(
    source=source,
    entities=[merchant],
    tags=["merchants", "daily"],
    description="Total spend by merchant ID",
    timestamp="transaction_date",
    interval=timedelta(days=1),
    metrics=[spend_metrics],
    validators={"amt": [mlf.greater_than_or_equal(value=0)]},
)
def merchant_spend_1d_interval(df: pl.DataFrame) -> pl.DataFrame:
    # merchant_id is auto-generated by the engine from the merchant entity
    return df.select(
        pl.col("merchant_id"),
        pl.col("trans_date_trans_time")
        .str.to_datetime("%Y-%m-%d %H:%M:%S")
        .alias("transaction_date"),
        pl.col("amt"),
    )


### ACCOUNT FEATURES


@mlf.feature(
    source=source,
    entities=[account],
    tags=["accounts", "weekly"],
    description="Total spend by account ID",
    timestamp="transaction_date",
    interval="7d",
    metrics=[spend_metrics],
)
def account_spend_7d_interval(df: pl.DataFrame) -> pl.DataFrame:
    # account_id is auto-generated by the engine from the account entity
    return df.select(
        pl.col("account_id"),
        pl.col("trans_date_trans_time")
        .str.to_datetime("%Y-%m-%d %H:%M:%S")
        .alias("transaction_date"),
        pl.col("amt"),
    )


### USER FEATURES


@mlf.feature(
    source=source,
    entities=[user],
    tags=["users", "monthly"],
    description="Total spend by user ID",
    timestamp="transaction_date",
    interval=timedelta(days=30),
    metrics=[spend_metrics],
)
def user_spend_30d_interval(df: pl.DataFrame) -> pl.DataFrame:
    # user_id is auto-generated by the engine from the user entity
    return df.select(
        pl.col("user_id"),
        pl.col("trans_date_trans_time")
        .str.to_datetime("%Y-%m-%d %H:%M:%S")
        .alias("transaction_date"),
        pl.col("amt"),
    )
